// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgS5qoRvsEgTUcQ8-5C02FMrQxWFA_BDk',
    appId: '1:935562013319:web:d17519afe7516636dda622',
    messagingSenderId: '935562013319',
    projectId: 'minimalist-attendance-tracker',
    authDomain: 'minimalist-attendance-tracker.firebaseapp.com',
    storageBucket: 'minimalist-attendance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-aYLLqX1Y7PIPmFJWQmeEAN9a0EMbjK8',
    appId: '1:935562013319:android:95314e7e5bc92cbddda622',
    messagingSenderId: '935562013319',
    projectId: 'minimalist-attendance-tracker',
    storageBucket: 'minimalist-attendance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDragN_Ll3MwCYMSjGJaVGXFG1qCgK8SVU',
    appId: '1:935562013319:ios:6d6918403f4a284adda622',
    messagingSenderId: '935562013319',
    projectId: 'minimalist-attendance-tracker',
    storageBucket: 'minimalist-attendance-tracker.firebasestorage.app',
    iosBundleId: 'com.example.minimalistAttendanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxyweVxvUceGRmFTMb7qYcjbeFVptnWs',
    appId: '1:536284260911:ios:42fdb1b119af9904af34da',
    messagingSenderId: '536284260911',
    projectId: 'fbflutter-af130',
    storageBucket: 'fbflutter-af130.firebasestorage.app',
    iosBundleId: 'com.example.minimalistAttendanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7hhkehznuoCPMqjCVO0tl7smBh5fiBb0',
    appId: '1:536284260911:web:66e0aff494bb5cc1af34da',
    messagingSenderId: '536284260911',
    projectId: 'fbflutter-af130',
    authDomain: 'fbflutter-af130.firebaseapp.com',
    storageBucket: 'fbflutter-af130.firebasestorage.app',
  );
}